lalaal

diff --git a/.github/workflows/version_bump.yml b/.github/workflows/version_bump.yml
--- a/.github/workflows/version_bump.yml
+++ b/.github/workflows/version_bump.yml
@@ -29,9 +29,51 @@ jobs:
         git fetch --tags  # Fetch all tags from the remote repository
         latest_version=$(git tag --list --sort=-v:refname | head -n 1)
         echo "Latest version: $latest_version"
+          continue-on-error: true
+
+    - name: Determine New Version
+      id: determine_version
+      run: |
+        release_type="${{ github.event.inputs.release_type }}"
+        latest_version="${latest_version}"
+
+        # Split the latest version into its components
+        IFS='.' read -ra version_parts <<< "$latest_version"
+        major="${version_parts[0]}"
+        minor="${version_parts[1]}"
+        patch="${version_parts[2]}"
+        config="${version_parts[3]}"
+
+        case $release_type in
+          "major")
+            major=$((major + 1))
+            minor=0
+            patch=0
+            config=0
+            ;;
+          "minor")
+            minor=$((minor + 1))
+            patch=0
+            config=0
+            ;;
+          "patch")
+            patch=$((patch + 1))
+            config=0
+            ;;
+          "config")
+            config=$((config + 1))
+            ;;
+          *)
+            echo "Invalid release_type: $release_type"
+            exit 1
+            ;;
+        esac
+
+        new_version="$major.$minor.$patch.$config"
+        echo "New version: $new_version"
       continue-on-error: true
 
-    
-      
-   
+
+
+
 
