final test

diff --git a/.github/workflows/version_bump.yml b/.github/workflows/version_bump.yml
--- a/.github/workflows/version_bump.yml
+++ b/.github/workflows/version_bump.yml
@@ -38,9 +38,38 @@ jobs:
       run: |
         echo "Latest version: ${LATEST_VERSION}"
         IFS='.' read -ra my_array <<< "${LATEST_VERSION}"
-        for item in "${my_array[@]}"; do
-          echo "$item"
-        done
+        major="${version_parts[0]}"
+        minor="${version_parts[1]}"
+        patch="${version_parts[2]}"
+        config="${version_parts[3]}"
+    
+        case $release_type in
+          "major")
+            major=$((major + 1))
+            minor=0
+            patch=0
+            config=0
+            ;;
+          "minor")
+            minor=$((minor + 1))
+            patch=0
+            config=0
+            ;;
+          "patch")
+            patch=$((patch + 1))
+            config=0
+            ;;
+          "config")
+            config=$((config + 1))
+            ;;
+          *)
+            echo "Invalid release_type: $release_type"
+            exit 1
+            ;;
+        esac
+    
+        new_version="$major.$minor.$patch.$config"
+        echo "New version: $new_version"
       continue-on-error: true
 
 
